web:
  port: 8080

storage:
  type: sqlite
  path: /data/data.db

endpoints:
  - name: Dermagroup - Prod
    group: ERP
    url: "https://erp-dermagroup.deepzide.com"
    interval: 1m
    conditions:
      - "[STATUS] > 0"
      - "[STATUS] < 500"
  - name: Dermagroup - Dev
    group: ERP
    url: "https://erp-dermagroup-dev.deepzide.com"
    interval: 1m
    conditions:
      - "[STATUS] > 0"
      - "[STATUS] < 500"
  - name: Cheese - Prod
    group: ERP
    url: "https://erp-cheese.deepzide.com"
    interval: 1m
    conditions:
      - "[STATUS] > 0"
      - "[STATUS] < 500"
  - name: Acuamania - Prod
    group: ERP
    url: "https://erp-acuamania.deepzide.com"
    interval: 1m
    conditions:
      - "[STATUS] > 0"
      - "[STATUS] < 500"
  - name: TM - API
    group: Todomercado
    url: "https://p4d8jtoinl.execute-api.us-east-1.amazonaws.com/health"
    interval: 1m
    conditions:
      - "[STATUS] > 0"
      - "[STATUS] < 500"
  - name: Alloy
    group: observabilty
    url: "https://alloy.deepzide.com"
    interval: 1m
    conditions:
      - "[STATUS] > 0"
      - "[STATUS] < 500"
  - name: Loki
    group: observabilty
    url: "https://loki.deepzide.com"
    interval: 1m
    conditions:
      - "[STATUS] > 0"
      - "[STATUS] < 500"
  - name: Grafana
    group: observabilty
    url: "https://grafana.deepzide.com"
    interval: 1m
    conditions:
      - "[STATUS] > 0"
      - "[STATUS] < 500"
